/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import configuracion.Gestionar;
import entidades.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Gerard
 */
public class frmMenu extends javax.swing.JFrame {
    public static Usuario usuarioActual;
    private final Validaciones validar;
    
    /**
     * Creates new form frmMenuPrincipal
     */

    public frmMenu() {
        this.validar = new Validaciones();
        initComponents();
        lblEmpleado.setText(usuarioActual.getEmpleado().toString()); 
        setTitle(new configuracion.Gestionar().Leer("Empresa","nombre"));
        validar.iniciarSesion(usuarioActual, jmbPrincipal.getSubElements());
        ActionListener updateClockAction = (ActionEvent e) -> {
            Locale local = new Locale("es", "SV");
            SimpleDateFormat formateador = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy - hh:mm:ss a", local);
            lblReloj.setText(formateador.format(new Date()).trim()); 
        };
        Timer t = new Timer(100, updateClockAction);
        t.start();
        tblSesion.setFloatable(false);
        jMenuCaja.setVisible(false);
        jMenuAyuda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblSesion = new javax.swing.JToolBar();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        lblEmpleado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        lblReloj = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuUsuCon = new javax.swing.JMenuItem();
        jMenuCambiarUsu = new javax.swing.JMenuItem();
        jMenuCaja = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuSalir = new javax.swing.JMenuItem();
        menuOperaciones = new javax.swing.JMenu();
        smClientes = new javax.swing.JMenuItem();
        smProveedores = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miProducto = new javax.swing.JMenuItem();
        smCompras = new javax.swing.JMenuItem();
        smVentas = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        smInventario = new javax.swing.JMenuItem();
        jMenuAjustInv = new javax.swing.JMenuItem();
        smCorteCaja = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        menuConsultas = new javax.swing.JMenu();
        smConsCompras = new javax.swing.JMenuItem();
        smConsVentas = new javax.swing.JMenuItem();
        smConsProveedores = new javax.swing.JMenuItem();
        smConsClientes = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuAjusteInv = new javax.swing.JMenuItem();
        jMenuConsCaja = new javax.swing.JMenuItem();
        jMenuMovimiento = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        smProcPrecios = new javax.swing.JMenuItem();
        smProcExportar = new javax.swing.JMenuItem();
        jMenuImportar = new javax.swing.JMenuItem();
        jMenuCategorias = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuReportes = new javax.swing.JMenu();
        smReportCompras = new javax.swing.JMenuItem();
        smReportVentas = new javax.swing.JMenuItem();
        jMenuMovimientos = new javax.swing.JMenuItem();
        smReporCortes = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        smReportBodegas = new javax.swing.JMenuItem();
        smReportPrecios = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        smReportClientes = new javax.swing.JMenuItem();
        jMenuProveedores = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuSistema = new javax.swing.JMenu();
        smAdministrar = new javax.swing.JMenu();
        smAdmEmpleado = new javax.swing.JMenuItem();
        smAdmUsuarios = new javax.swing.JMenuItem();
        smAdRoles = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        smEmpresa = new javax.swing.JMenuItem();
        smImpresora = new javax.swing.JMenuItem();
        smUnidades = new javax.swing.JMenuItem();
        jMenuAdCategorias = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblSesion.add(jSeparator13);

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpleado.setText("jLabel1");
        tblSesion.add(lblEmpleado);

        jSeparator1.setMaximumSize(new java.awt.Dimension(9, 32767));
        jSeparator1.setPreferredSize(new java.awt.Dimension(9, 0));
        tblSesion.add(jSeparator1);

        lblReloj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReloj.setText("jLabel1");
        lblReloj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblReloj.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tblSesion.add(lblReloj);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/open24.png"))); // NOI18N
        jMenuInicio.setText("Inicio");
        jMenuInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuUsuCon.setText("Usuarios Conectados");
        jMenuInicio.add(jMenuUsuCon);

        jMenuCambiarUsu.setText("Cambiar de Usuario");
        jMenuInicio.add(jMenuCambiarUsu);

        jMenuCaja.setText("Cambiar de Caja");
        jMenuInicio.add(jMenuCaja);
        jMenuInicio.add(jSeparator11);

        jMenuSalir.setText("Salir del Sistema");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuSalir);

        jmbPrincipal.add(jMenuInicio);

        menuOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/operation.png"))); // NOI18N
        menuOperaciones.setText("Operaciones");
        menuOperaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        smClientes.setText("Clientes");
        smClientes.setEnabled(false);
        smClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smClientesActionPerformed(evt);
            }
        });
        menuOperaciones.add(smClientes);

        smProveedores.setText("Proveedores");
        smProveedores.setEnabled(false);
        smProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smProveedoresActionPerformed(evt);
            }
        });
        menuOperaciones.add(smProveedores);
        menuOperaciones.add(jSeparator2);

        miProducto.setText("Articulos");
        miProducto.setEnabled(false);
        miProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductoActionPerformed(evt);
            }
        });
        menuOperaciones.add(miProducto);

        smCompras.setText("Compras");
        smCompras.setEnabled(false);
        smCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smComprasActionPerformed(evt);
            }
        });
        menuOperaciones.add(smCompras);

        smVentas.setText("Ventas");
        smVentas.setEnabled(false);
        smVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smVentasActionPerformed(evt);
            }
        });
        menuOperaciones.add(smVentas);
        menuOperaciones.add(jSeparator10);

        smInventario.setText("Inventario Inicial");
        smInventario.setEnabled(false);
        smInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smInventarioActionPerformed(evt);
            }
        });
        menuOperaciones.add(smInventario);

        jMenuAjustInv.setText("Ajuste de Inventario");
        jMenuAjustInv.setEnabled(false);
        menuOperaciones.add(jMenuAjustInv);

        smCorteCaja.setText("Corte de Caja");
        smCorteCaja.setEnabled(false);
        smCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smCorteCajaActionPerformed(evt);
            }
        });
        menuOperaciones.add(smCorteCaja);
        menuOperaciones.add(jSeparator12);

        jmbPrincipal.add(menuOperaciones);

        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/consultas32.png"))); // NOI18N
        menuConsultas.setText("Consultas");
        menuConsultas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        smConsCompras.setText("Compras");
        smConsCompras.setEnabled(false);
        smConsCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smConsComprasActionPerformed(evt);
            }
        });
        menuConsultas.add(smConsCompras);

        smConsVentas.setText("Ventas");
        smConsVentas.setEnabled(false);
        smConsVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smConsVentasActionPerformed(evt);
            }
        });
        menuConsultas.add(smConsVentas);

        smConsProveedores.setText("Proveedores");
        smConsProveedores.setEnabled(false);
        smConsProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smConsProveedoresActionPerformed(evt);
            }
        });
        menuConsultas.add(smConsProveedores);

        smConsClientes.setText("Clientes");
        smConsClientes.setEnabled(false);
        menuConsultas.add(smConsClientes);
        menuConsultas.add(jSeparator9);

        jMenuAjusteInv.setText("Ajuste de Inventario");
        jMenuAjusteInv.setEnabled(false);
        menuConsultas.add(jMenuAjusteInv);

        jMenuConsCaja.setText("Caja");
        jMenuConsCaja.setEnabled(false);
        menuConsultas.add(jMenuConsCaja);

        jMenuMovimiento.setText("Movimientos");
        jMenuMovimiento.setEnabled(false);
        menuConsultas.add(jMenuMovimiento);

        jmbPrincipal.add(menuConsultas);

        menuProcesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/procesos.png"))); // NOI18N
        menuProcesos.setText("Procesos");
        menuProcesos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        smProcPrecios.setText("Actualizacion de Precios");
        smProcPrecios.setEnabled(false);
        menuProcesos.add(smProcPrecios);

        smProcExportar.setText("Exportar a Excel");
        smProcExportar.setEnabled(false);
        menuProcesos.add(smProcExportar);

        jMenuImportar.setText("Importar désde Excel");
        jMenuImportar.setEnabled(false);
        menuProcesos.add(jMenuImportar);

        jMenuCategorias.setText("Ajustar Categorias");
        jMenuCategorias.setEnabled(false);
        jMenuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCategoriasActionPerformed(evt);
            }
        });
        menuProcesos.add(jMenuCategorias);
        menuProcesos.add(jSeparator8);

        jmbPrincipal.add(menuProcesos);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/report.png"))); // NOI18N
        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        smReportCompras.setText("Compras");
        smReportCompras.setEnabled(false);
        menuReportes.add(smReportCompras);

        smReportVentas.setText("Ventas");
        smReportVentas.setEnabled(false);
        menuReportes.add(smReportVentas);

        jMenuMovimientos.setText("Movimientos");
        jMenuMovimientos.setEnabled(false);
        menuReportes.add(jMenuMovimientos);

        smReporCortes.setText("Cortes de Caja");
        smReporCortes.setEnabled(false);
        menuReportes.add(smReporCortes);
        menuReportes.add(jSeparator3);

        smReportBodegas.setText("Bodegas y Costos");
        smReportBodegas.setToolTipText("Bodegas y Costos de Productos");
        smReportBodegas.setEnabled(false);
        menuReportes.add(smReportBodegas);

        smReportPrecios.setText("Lista de Precios");
        smReportPrecios.setToolTipText("Listado de Precios");
        smReportPrecios.setEnabled(false);
        menuReportes.add(smReportPrecios);
        menuReportes.add(jSeparator4);

        smReportClientes.setText("Clientes");
        smReportClientes.setToolTipText("Catalogo de Clientes");
        smReportClientes.setEnabled(false);
        menuReportes.add(smReportClientes);

        jMenuProveedores.setText("Proveedores");
        jMenuProveedores.setToolTipText("Catalogo de Proveedores");
        jMenuProveedores.setEnabled(false);
        menuReportes.add(jMenuProveedores);
        menuReportes.add(jSeparator7);

        jmbPrincipal.add(menuReportes);

        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/config32.png"))); // NOI18N
        menuSistema.setText("Configuracion");
        menuSistema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        smAdministrar.setText("Administrar");
        smAdministrar.setEnabled(false);
        smAdministrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        smAdmEmpleado.setText("Empleados");
        smAdmEmpleado.setEnabled(false);
        smAdmEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAdmEmpleadoActionPerformed(evt);
            }
        });
        smAdministrar.add(smAdmEmpleado);

        smAdmUsuarios.setText("Usuarios");
        smAdmUsuarios.setEnabled(false);
        smAdmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAdmUsuariosActionPerformed(evt);
            }
        });
        smAdministrar.add(smAdmUsuarios);

        smAdRoles.setText("Roles");
        smAdRoles.setEnabled(false);
        smAdRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAdRolesActionPerformed(evt);
            }
        });
        smAdministrar.add(smAdRoles);

        menuSistema.add(smAdministrar);
        menuSistema.add(jSeparator5);

        smEmpresa.setText("Datos de Empresa");
        smEmpresa.setEnabled(false);
        menuSistema.add(smEmpresa);

        smImpresora.setText("Configurar Impresora");
        smImpresora.setEnabled(false);
        menuSistema.add(smImpresora);

        smUnidades.setText("Unidades");
        smUnidades.setEnabled(false);
        smUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smUnidadesActionPerformed(evt);
            }
        });
        menuSistema.add(smUnidades);

        jMenuAdCategorias.setText("Categorias");
        jMenuAdCategorias.setEnabled(false);
        jMenuAdCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdCategoriasActionPerformed(evt);
            }
        });
        menuSistema.add(jMenuAdCategorias);
        menuSistema.add(jSeparator6);

        jmbPrincipal.add(menuSistema);

        jMenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Help_icon-32x32.png"))); // NOI18N
        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("Manual de Usuario");
        jMenuAyuda.add(jMenuItem1);

        jMenuItem2.setText("Actualizaciones");
        jMenuAyuda.add(jMenuItem2);

        jMenuItem3.setText("Acerca De...");
        jMenuAyuda.add(jMenuItem3);

        jmbPrincipal.add(jMenuAyuda);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smProveedoresActionPerformed
        // TODO add your handling code here:
        frmProveedor frmPr = new frmProveedor();
        frmPr.pack();
        desktop.add(frmPr);
        for (JInternalFrame allFrame : desktop.getAllFrames()) {
            if (allFrame.getTitle().equalsIgnoreCase(frmPr.getTitle())) {
                if (allFrame.isVisible()) {
                    JOptionPane.showMessageDialog(this, "Este formulario ya esta abierto", new configuracion.Gestionar().Leer("Empresa", "Nombre"), JOptionPane.INFORMATION_MESSAGE);
                } else {
                    frmPr.setVisible(true);
                }
                break;
            }
        }
        try {
            frmPr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smProveedoresActionPerformed

    private void miProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductoActionPerformed
        // TODO add your handling code here:
        frmProducto frmP = new frmProducto();
        frmP.pack();
        desktop.add(frmP);
        for (JInternalFrame allFrame : desktop.getAllFrames()) {
            if (allFrame.getTitle().equalsIgnoreCase(frmP.getTitle())) {
                if (allFrame.isVisible()) {
                    JOptionPane.showMessageDialog(this, "Este formulario ya esta abierto", new configuracion.Gestionar().Leer("Empresa", "Nombre"), JOptionPane.INFORMATION_MESSAGE);
                } else {
                    frmP.setVisible(true);
                }
                break;
            }
        }
        try {
            frmP.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miProductoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void smClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smClientesActionPerformed
        // TODO add your handling code here:
        frmClientes frmC = new frmClientes();
        frmC.pack();
        desktop.add(frmC);
        for (JInternalFrame allFrame : desktop.getAllFrames()) {
            if (allFrame.getTitle().equalsIgnoreCase(frmC.getTitle())) {
                if (allFrame.isVisible()) {
                    JOptionPane.showMessageDialog(this, "Este formulario ya esta abierto", new configuracion.Gestionar().Leer("Empresa", "Nombre"), JOptionPane.INFORMATION_MESSAGE);
                } else {
                    frmC.setVisible(true);
                }
                break;
            }
        }
        try {
            frmC.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smClientesActionPerformed

    private void smVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smVentasActionPerformed
        // TODO add your handling code here:      
        frmVentas internalFrame = new frmVentas();
        internalFrame.pack();
        desktop.add(internalFrame);
        for (JInternalFrame allFrame : desktop.getAllFrames()) {
            if (allFrame.getTitle().equalsIgnoreCase(internalFrame.getTitle())) {
                if (allFrame.isVisible()) {
                    JOptionPane.showMessageDialog(this, "Este formulario ya esta abierto", new configuracion.Gestionar().Leer("Empresa", "Nombre"), JOptionPane.INFORMATION_MESSAGE);
                } else {
                    internalFrame.setVisible(true);
                }
                break;
            }
        }
        try {
            internalFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smVentasActionPerformed

    private void smComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smComprasActionPerformed
        // TODO add your handling code here:
        frmCompra frmCr = new frmCompra();
        frmCr.pack();
        desktop.add(frmCr);
        for (JInternalFrame allFrame : desktop.getAllFrames()) {
            if (allFrame.getTitle().equalsIgnoreCase(frmCr.getTitle())) {
                if (allFrame.isVisible()) {
                    JOptionPane.showMessageDialog(this, "Este formulario ya esta abierto", new configuracion.Gestionar().Leer("Empresa", "Nombre"), JOptionPane.INFORMATION_MESSAGE);
                } else {
                    frmCr.setVisible(true);
                }
                break;
            }
        }
        try {
            frmCr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smComprasActionPerformed

    private void smCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smCorteCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smCorteCajaActionPerformed

    private void smConsComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smConsComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smConsComprasActionPerformed

    private void smConsVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smConsVentasActionPerformed
        // TODO add your handling code here:
        frmConsultarVentas frmCV = new frmConsultarVentas();
        frmCV.pack();
        desktop.add(frmCV);
                if(frmCV.isVisible()){
            System.out.println("Esta abierto");
        } else {            
            frmCV.setVisible(true);
        }
        try {
            frmCV.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smConsVentasActionPerformed

    private void smConsProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smConsProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smConsProveedoresActionPerformed

    private void smUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smUnidadesActionPerformed
        // TODO add your handling code here:
        frmUnidades frmU = new frmUnidades();
                frmU.pack();
        desktop.add(frmU);
                if(frmU.isVisible()){
            System.out.println("Esta abierto");
        } else {            
            frmU.setVisible(true);
        }
        try {
            frmU.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smUnidadesActionPerformed

    private void smAdRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAdRolesActionPerformed
        // TODO add your handling code here:
        frmNiveles frmR = new frmNiveles();
        frmR.pack();
        desktop.add(frmR);
            if(frmR.isVisible()){
            System.out.println("Esta abierto");
        } else {            
            frmR.setVisible(true);
        }
        try {
            frmR.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smAdRolesActionPerformed

    private void smInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smInventarioActionPerformed

    private void smAdmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAdmUsuariosActionPerformed
        // TODO add your handling code here:
        frmUsuarios frmUsu = new frmUsuarios();
        frmUsu.pack();
        desktop.add(frmUsu);
                if(frmUsu.isVisible()){
            System.out.println("Esta abierto");
        } else {            
            frmUsu.setVisible(true);
        }
        try {
            frmUsu.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smAdmUsuariosActionPerformed

    private void jMenuAdCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdCategoriasActionPerformed
        // TODO add your handling code here:
        frmCategorias frmCa = new frmCategorias();
        frmCa.pack();
        desktop.add(frmCa);
                if(frmCa.isVisible()){
            System.out.println("Esta abierto");
        } else {            
            frmCa.setVisible(true);
        }
        try {
            frmCa.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuAdCategoriasActionPerformed

    private void smAdmEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAdmEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smAdmEmpleadoActionPerformed

    private void jMenuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCategoriasActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estas seguro que desea salir del Sistema?",
            new Gestionar().Leer("Empresa", "nombre"),
                    JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION)
                    {
                        System.exit( 0 ); 
                    }
    }//GEN-LAST:event_jMenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem jMenuAdCategorias;
    private javax.swing.JMenuItem jMenuAjustInv;
    private javax.swing.JMenuItem jMenuAjusteInv;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuItem jMenuCaja;
    private javax.swing.JMenuItem jMenuCambiarUsu;
    private javax.swing.JMenuItem jMenuCategorias;
    private javax.swing.JMenuItem jMenuConsCaja;
    private javax.swing.JMenuItem jMenuImportar;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuMovimiento;
    private javax.swing.JMenuItem jMenuMovimientos;
    private javax.swing.JMenuItem jMenuProveedores;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jMenuUsuCon;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuOperaciones;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenuItem miProducto;
    private javax.swing.JMenuItem smAdRoles;
    private javax.swing.JMenuItem smAdmEmpleado;
    private javax.swing.JMenuItem smAdmUsuarios;
    private javax.swing.JMenu smAdministrar;
    private javax.swing.JMenuItem smClientes;
    private javax.swing.JMenuItem smCompras;
    private javax.swing.JMenuItem smConsClientes;
    private javax.swing.JMenuItem smConsCompras;
    private javax.swing.JMenuItem smConsProveedores;
    private javax.swing.JMenuItem smConsVentas;
    private javax.swing.JMenuItem smCorteCaja;
    private javax.swing.JMenuItem smEmpresa;
    private javax.swing.JMenuItem smImpresora;
    private javax.swing.JMenuItem smInventario;
    private javax.swing.JMenuItem smProcExportar;
    private javax.swing.JMenuItem smProcPrecios;
    private javax.swing.JMenuItem smProveedores;
    private javax.swing.JMenuItem smReporCortes;
    private javax.swing.JMenuItem smReportBodegas;
    private javax.swing.JMenuItem smReportClientes;
    private javax.swing.JMenuItem smReportCompras;
    private javax.swing.JMenuItem smReportPrecios;
    private javax.swing.JMenuItem smReportVentas;
    private javax.swing.JMenuItem smUnidades;
    private javax.swing.JMenuItem smVentas;
    private javax.swing.JToolBar tblSesion;
    // End of variables declaration//GEN-END:variables
}
