/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import entidades.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Gerard
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
    public static Usuario usuarioActual;
    private Validaciones validar;
    
    /**
     * Creates new form frmMenuPrincipal
     */

    public frmMenuPrincipal() {
        this.validar = new Validaciones();
        initComponents();
        lblEmpleado.setText(usuarioActual.getEmpleado().toString()); 
        setTitle(new configuracion.Gestionar().Leer("Empresa","nombre"));
        validar.iniciarSesion(usuarioActual, jmbPrincipal.getSubElements());
        ActionListener updateClockAction = (ActionEvent e) -> {
            Locale local = new Locale("es", "SV");
            SimpleDateFormat formateador = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy - hh:mm:ss a", local);
            lblReloj.setText(formateador.format(new Date()).trim()); 
        };
        Timer t = new Timer(100, updateClockAction);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblSesion = new javax.swing.JToolBar();
        lblEmpleado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        lblReloj = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        menuOperaciones = new javax.swing.JMenu();
        miProducto = new javax.swing.JMenuItem();
        smClientes = new javax.swing.JMenuItem();
        smProveedores = new javax.swing.JMenuItem();
        smCompras = new javax.swing.JMenuItem();
        smVentas = new javax.swing.JMenuItem();
        smInventario = new javax.swing.JMenuItem();
        smCorteCaja = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        smConsCompras = new javax.swing.JMenuItem();
        smConsVentas = new javax.swing.JMenuItem();
        smConsProveedores = new javax.swing.JMenuItem();
        smConsClientes = new javax.swing.JMenuItem();
        smConsArticulos = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        smProcRespaldos = new javax.swing.JMenuItem();
        smProcImportar = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        smReportVentas = new javax.swing.JMenuItem();
        smReportCompras = new javax.swing.JMenuItem();
        smReportProveedor = new javax.swing.JMenuItem();
        smReportArticulos = new javax.swing.JMenuItem();
        smReportClientes = new javax.swing.JMenuItem();
        smReportFarmacias = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        smAdministrar = new javax.swing.JMenu();
        smAdmEmpleado = new javax.swing.JMenuItem();
        smAdmUsuarios = new javax.swing.JMenuItem();
        smAdRoles = new javax.swing.JMenuItem();
        smEmpresa = new javax.swing.JMenuItem();
        smImpresora = new javax.swing.JMenuItem();
        smUnidades = new javax.swing.JMenuItem();
        smCaja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmpleado.setText("jLabel1");
        tblSesion.add(lblEmpleado);
        tblSesion.add(jSeparator1);

        lblReloj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReloj.setText("jLabel1");
        lblReloj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblReloj.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tblSesion.add(lblReloj);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        menuOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/operation.png"))); // NOI18N
        menuOperaciones.setText("Operaciones");
        menuOperaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miProducto.setText("Articulos");
        miProducto.setEnabled(false);
        miProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductoActionPerformed(evt);
            }
        });
        menuOperaciones.add(miProducto);

        smClientes.setText("Clientes");
        smClientes.setEnabled(false);
        smClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smClientesActionPerformed(evt);
            }
        });
        menuOperaciones.add(smClientes);

        smProveedores.setText("Proveedores");
        smProveedores.setEnabled(false);
        smProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smProveedoresActionPerformed(evt);
            }
        });
        menuOperaciones.add(smProveedores);

        smCompras.setText("Compras");
        smCompras.setEnabled(false);
        smCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smComprasActionPerformed(evt);
            }
        });
        menuOperaciones.add(smCompras);

        smVentas.setText("Ventas");
        smVentas.setEnabled(false);
        smVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smVentasActionPerformed(evt);
            }
        });
        menuOperaciones.add(smVentas);

        smInventario.setText("Inventario Inicial");
        smInventario.setEnabled(false);
        menuOperaciones.add(smInventario);

        smCorteCaja.setText("Corte de Caja");
        smCorteCaja.setEnabled(false);
        smCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smCorteCajaActionPerformed(evt);
            }
        });
        menuOperaciones.add(smCorteCaja);

        jmbPrincipal.add(menuOperaciones);

        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/consultas32.png"))); // NOI18N
        menuConsultas.setText("Consultas");
        menuConsultas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        smConsCompras.setText("Compras");
        smConsCompras.setEnabled(false);
        smConsCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smConsComprasActionPerformed(evt);
            }
        });
        menuConsultas.add(smConsCompras);

        smConsVentas.setText("Ventas");
        smConsVentas.setEnabled(false);
        smConsVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smConsVentasActionPerformed(evt);
            }
        });
        menuConsultas.add(smConsVentas);

        smConsProveedores.setText("Proveedores");
        smConsProveedores.setEnabled(false);
        smConsProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smConsProveedoresActionPerformed(evt);
            }
        });
        menuConsultas.add(smConsProveedores);

        smConsClientes.setText("Clientes");
        smConsClientes.setEnabled(false);
        menuConsultas.add(smConsClientes);

        smConsArticulos.setText("Articulos");
        smConsArticulos.setEnabled(false);
        menuConsultas.add(smConsArticulos);

        jmbPrincipal.add(menuConsultas);

        menuProcesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/procesos.png"))); // NOI18N
        menuProcesos.setText("Procesos");
        menuProcesos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        smProcRespaldos.setText("Respaldos");
        smProcRespaldos.setEnabled(false);
        menuProcesos.add(smProcRespaldos);

        smProcImportar.setText("Importar de Excel");
        smProcImportar.setEnabled(false);
        menuProcesos.add(smProcImportar);

        jmbPrincipal.add(menuProcesos);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/report.png"))); // NOI18N
        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        smReportVentas.setText("Ventas");
        smReportVentas.setEnabled(false);
        menuReportes.add(smReportVentas);

        smReportCompras.setText("Compras");
        smReportCompras.setEnabled(false);
        menuReportes.add(smReportCompras);

        smReportProveedor.setText("Proveedores");
        smReportProveedor.setEnabled(false);
        menuReportes.add(smReportProveedor);

        smReportArticulos.setText("Articulos");
        smReportArticulos.setEnabled(false);
        menuReportes.add(smReportArticulos);

        smReportClientes.setText("Clientes");
        smReportClientes.setEnabled(false);
        menuReportes.add(smReportClientes);

        smReportFarmacias.setText("Farmacias");
        smReportFarmacias.setEnabled(false);
        menuReportes.add(smReportFarmacias);

        jmbPrincipal.add(menuReportes);

        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/config32.png"))); // NOI18N
        menuSistema.setText("Sistema");
        menuSistema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        smAdministrar.setText("Administrar");
        smAdministrar.setEnabled(false);
        smAdministrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        smAdmEmpleado.setText("Empleados");
        smAdmEmpleado.setEnabled(false);
        smAdministrar.add(smAdmEmpleado);

        smAdmUsuarios.setText("Usuarios");
        smAdmUsuarios.setEnabled(false);
        smAdministrar.add(smAdmUsuarios);

        smAdRoles.setText("Roles");
        smAdRoles.setEnabled(false);
        smAdRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAdRolesActionPerformed(evt);
            }
        });
        smAdministrar.add(smAdRoles);

        menuSistema.add(smAdministrar);

        smEmpresa.setText("Empresa");
        smEmpresa.setEnabled(false);
        menuSistema.add(smEmpresa);

        smImpresora.setText("Impresora");
        smImpresora.setEnabled(false);
        menuSistema.add(smImpresora);

        smUnidades.setText("Unidades");
        smUnidades.setEnabled(false);
        smUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smUnidadesActionPerformed(evt);
            }
        });
        menuSistema.add(smUnidades);

        smCaja.setText("Caja");
        smCaja.setEnabled(false);
        smCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smCajaActionPerformed(evt);
            }
        });
        menuSistema.add(smCaja);

        jmbPrincipal.add(menuSistema);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smProveedoresActionPerformed
        // TODO add your handling code here:
        frmProveedor frm = new frmProveedor();
        frm.setVisible(true);
    }//GEN-LAST:event_smProveedoresActionPerformed

    private void miProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductoActionPerformed
        // TODO add your handling code here:
        frmProductos frm = new frmProductos();
        frm.setVisible(true);
    }//GEN-LAST:event_miProductoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void smClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smClientesActionPerformed
        // TODO add your handling code here:
        frmCliente frmC = new frmCliente();
        frmC.setVisible(true);
    }//GEN-LAST:event_smClientesActionPerformed

    private void smVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smVentasActionPerformed
        // TODO add your handling code here:      
        frmVentas internalFrame = new frmVentas();
        internalFrame.pack();
        desktop.add(internalFrame);
        if(internalFrame.isVisible()){
            System.out.println("Esta abierto");
        } else {            
            internalFrame.setVisible(true);
        }
        try {
            internalFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_smVentasActionPerformed

    private void smComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smComprasActionPerformed
        // TODO add your handling code here:
        frmCompra frmC = new frmCompra();
        frmC.setVisible(true);
    }//GEN-LAST:event_smComprasActionPerformed

    private void smCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smCorteCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smCorteCajaActionPerformed

    private void smConsComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smConsComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smConsComprasActionPerformed

    private void smConsVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smConsVentasActionPerformed
        // TODO add your handling code here:
        frmConsultarVentas frmCV = new frmConsultarVentas();
        frmCV.setVisible(true);
    }//GEN-LAST:event_smConsVentasActionPerformed

    private void smConsProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smConsProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smConsProveedoresActionPerformed

    private void smUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smUnidadesActionPerformed
        // TODO add your handling code here:
        frmUnidades frmU = new frmUnidades();
        frmU.setVisible(true);
    }//GEN-LAST:event_smUnidadesActionPerformed

    private void smCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smCajaActionPerformed
        // TODO add your handling code here:
        frmCaja frmC = new frmCaja();
        frmC.setVisible(true);
    }//GEN-LAST:event_smCajaActionPerformed

    private void smAdRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAdRolesActionPerformed
        // TODO add your handling code here:
//        frmRoles frmR = new frmRoles();
//        frmR.setVisible(true);
    }//GEN-LAST:event_smAdRolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuOperaciones;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenuItem miProducto;
    private javax.swing.JMenuItem smAdRoles;
    private javax.swing.JMenuItem smAdmEmpleado;
    private javax.swing.JMenuItem smAdmUsuarios;
    private javax.swing.JMenu smAdministrar;
    private javax.swing.JMenuItem smCaja;
    private javax.swing.JMenuItem smClientes;
    private javax.swing.JMenuItem smCompras;
    private javax.swing.JMenuItem smConsArticulos;
    private javax.swing.JMenuItem smConsClientes;
    private javax.swing.JMenuItem smConsCompras;
    private javax.swing.JMenuItem smConsProveedores;
    private javax.swing.JMenuItem smConsVentas;
    private javax.swing.JMenuItem smCorteCaja;
    private javax.swing.JMenuItem smEmpresa;
    private javax.swing.JMenuItem smImpresora;
    private javax.swing.JMenuItem smInventario;
    private javax.swing.JMenuItem smProcImportar;
    private javax.swing.JMenuItem smProcRespaldos;
    private javax.swing.JMenuItem smProveedores;
    private javax.swing.JMenuItem smReportArticulos;
    private javax.swing.JMenuItem smReportClientes;
    private javax.swing.JMenuItem smReportCompras;
    private javax.swing.JMenuItem smReportFarmacias;
    private javax.swing.JMenuItem smReportProveedor;
    private javax.swing.JMenuItem smReportVentas;
    private javax.swing.JMenuItem smUnidades;
    private javax.swing.JMenuItem smVentas;
    private javax.swing.JToolBar tblSesion;
    // End of variables declaration//GEN-END:variables
}
